### ISSUE TITLE
Infinite loop with slack notifications

### ISSUE THREAD

**Issue by jeremycopinlm** [kestra-io/plugin-notifications#109]
### Expected Behavior

 io.kestra.plugin.notifications.slack.SlackExecution creates an infinite loop
 
 
![image](https://github.com/kestra-io/plugin-notifications/assets/91942081/48531ea6-1e29-4f1a-b870-12a739034685)

### Environment Information

- Kestra Version: 0.12.3
- Plugin version: 0.12

### Example flow

  - id: slack_error_notification
    type: io.kestra.plugin.notifications.slack.SlackExecution
    url: "{{ namespace.slack.hook }}"
    channel: '#channel'
    customMessage: "Failure"

**Comment by anna-geller** [comment]
Hi Jeremy, this behavior is intended as the SlackExecution should only be used with a Flow trigger. if you want to send a Slack message from a task, you should use the SlackIncomingWebhook task instead: https://kestra.io/plugins/plugin-notifications/tasks/slack/io.kestra.plugin.notifications.slack.slackexecution
