### ISSUE TITLE
DiscordIncomingWebhook example not escaped correctly in documentation

### ISSUE THREAD

**Issue by larsgerber** [kestra-io/plugin-notifications#162]
### Expected Behavior

Hello everyone

While playing around with the Discord plugin, I saw that the [second example](
https://kestra.io/plugins/plugin-notifications/tasks/discord/io.kestra.plugin.notifications.discord.discordincomingwebhook) from the `DiscordIncomingWebhook` type is not displaying the JSON payload correctly.

Blind copying and pasting leads to an `Invalid YAML` error. The JSON is correctly escaped in the code itself.
https://github.com/kestra-io/plugin-notifications/blob/729414d24a1951b31f70838d5c03485ecdd39b9e/src/main/java/io/kestra/plugin/notifications/discord/DiscordIncomingWebhook.java#L81

### Actual Behaviour

The example is correctly escaped, so that a simple copy and paste leads to a successful request.

### Steps To Reproduce

1. copy example from documentation
2. paste into flow
3. warning from Kestra is displayed

### Environment Information

- Kestra Version: v0.18.9
- Plugin version: v0.18.0 
- Operating System (OS / Docker / Kubernetes): Docker version 26.1.3
- Java Version (If not docker):

**Comment by anna-geller** [comment]
thx a lot for the report!
