### ISSUE TITLE
[cosmetic] Kestra email format could use some cleanup

### ISSUE THREAD

**Issue by johnsturgeon** [kestra-io/plugin-notifications#163]
### Describe the issue

I set up an email alert and there are a couple issues:
1. the image in the resulting email is a bit blurry and misshapen
2. the backticks on the task indicate that it wants to be rendered as 'code' but it isn't
<img width="635" alt="image" src="https://github.com/kestra-io/plugin-notifications/assets/9746310/1831d747-e722-4e89-9261-8c86d7d32a17">

### Environment

- Kestra Version: 0.16.0
- Operating System (OS/Docker/Kubernetes): Docker
- Java Version (if you don't run kestra in Docker):

**Comment by Ben8t** [comment]
@sampath24-ss 
Transfered to proper repository.

I think you can find the HTML template [here](https://github.com/kestra-io/plugin-notifications/blob/master/src/main/resources/mail-template.hbs.peb), and how it is sent [here](https://github.com/kestra-io/plugin-notifications/blob/master/src/main/java/io/kestra/plugin/notifications/mail/MailExecution.java)

**Comment by MilosPaunovic** [comment]
@Ben8t Maybe it would be a good idea to create an issue on OSS repo with the list of all email designs that need improving and with designs for it, maybe someone from the community could work on it as it is pretty simple task, but will help us greatly.

https://github.com/kestra-io/kestra-ee/issues/1843

**Comment by sampath24-ss** [comment]
I've identified the issue and made the necessary changes. Unfortunately, I'm unable to run the project locally due to an issue with my machine, so I haven't been able to submit the PR yet. Just wanted to keep you updated. Thank you!

**Comment by sampath24-ss** [comment]
Hi, 
I raised a PR.

**Comment by Ben8t** [comment]
Thanks @sampath24-ss , can you linked it here in comment please :) ?

**Comment by MilosPaunovic** [comment]
https://github.com/kestra-io/plugin-notifications/pull/174

**Comment by MilosPaunovic** [comment]
Closed via https://github.com/kestra-io/plugin-notifications/pull/174.

**Comment by sampath24-ss** [comment]
Thanks for the support @Ben8t & @MilosPaunovic
