### ISSUE TITLE
Add a Sentry subplugin for alerting and notification 

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-notifications#89]
### Feature description

API reference: https://docs.sentry.io/api/alerts/ 

How to create API token: https://docs.sentry.io/api/guides/create-auth-token/

Docs about Sentry Alerts: https://docs.sentry.io/product/alerts/

**Comment by loicmathieu** [comment]
Done in https://github.com/kestra-io/plugin-notifications/pull/100
